spring:
  profiles:
    active: dev
jwt:
  secret: "your-64-bit-secure-key-in-base64"
  expiration: 86400000 # 24 hours
logging:
  level:
    org.springframework.security: DEBUG
    com.thewa.skooly: DEBUG